version: 2
 
sources:
  - name: coffee_shop
    freshness: # default freshness
    project: analytics-engineers-club
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
 
      - name: orders
        freshness: # default freshness
        columns:
          - name: id
            tests:
              - unique
              - not_null